### ISSUE TITLE
`dune build` error: library "curl" not found

### ISSUE THREAD

**Issue by crvdgc** [imandra-ai/ocaml-opentelemetry#30]
https://github.com/imandra-ai/ocaml-opentelemetry/blob/f436a1b1091bd42d636d37bf2ee87c6c10400f7d/src/client-ocurl/dune#L4

Is it a typo of `ocurl`?

**Comment by mattjbray** [comment]
The opam package is called `ocurl`, but the findlib library name is `curl`. The `dune` file needs to specify the library, so this is correct.

To install the right dependencies, try, from the root of this repo:
```
opam install ./opentelemetry-client-ocurl.opam --deps-only
```
