### ISSUE TITLE
Record exceptions when using Opentelemetry_trace

### ISSUE THREAD

**Issue by ajbt200128** [imandra-ai/ocaml-opentelemetry#71]
In the normal otel code, exceptions are reported properly [here](https://github.com/imandra-ai/ocaml-opentelemetry/blob/974ce75a6ef1c37b17dd4f4e17772bf205f43e53/src/core/opentelemetry.ml#L1134), but this doesn't happen in Opentelemetry_trace [here](https://github.com/imandra-ai/ocaml-opentelemetry/blob/main/src/trace/opentelemetry_trace.ml#L197-L207). Ideally these two functions are identical or near identical

**Comment by ajbt200128** [comment]
Related: https://github.com/imandra-ai/ocaml-opentelemetry/issues/50

**Comment by c-cube** [comment]
Does #72 solve your issue? :)

**Comment by ajbt200128** [comment]
yup! thanks so much
