### ISSUE TITLE
Allow choosing own source of randomness for Span ids

### ISSUE THREAD

**Issue by ajbt200128** [imandra-ai/ocaml-opentelemetry#79]
This is a bit of a weird issue, so feel free to close if it doesn't make sense, but when we use this library in combination with parmap, the [source of randomness](https://github.com/imandra-ai/ocaml-opentelemetry/blob/fdee7fe2dd1f91a8d1f78d6ce20d2bc86d555444/src/core/rand_bytes.ml#L2) for the span ids doesn't reset when parmap forks. This means the span IDs end up being the same across forks, so it would be nice if we used either the global random state so we could reset it manually, or if there was another way to reset the randoms state. Alternatively, maybe the random state should be a part of the backend/collector or some other data structure that can be re created!

**Comment by c-cube** [comment]
You can change `rand_bytes_8` and `rand_bytes_16` already (they're references), but it would be also reasonable to put the random state behind a reference so that it's easy to call `make_self_init()` again?

**Comment by ajbt200128** [comment]
Oh they're already refs! nice! I don't see a need for a 2nd way to re-init randomness, going to close
